global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app1'
    static_configs:
      - targets: ['app1:5000']
    metrics_path: /metrics

  - job_name: 'app2'
    static_configs:
      - targets: ['app2:3000']
    metrics_path: /metrics
