name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: |
          docker compose build

      - name: Up services
        run: |
          docker compose up -d
          sleep 10

      - name: Smoke tests
        run: ./tests/smoke.sh

      - name: Down
        if: always()
        run: docker compose down
