name: CI

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ main, developer ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Fix script permissions
        run: chmod +x tests/*.sh

      - name: Compose up (build)
        run: |
          docker compose up -d --build
          docker compose ps
          # aguarda serviços principais
          for i in {1..40}; do
            UP=$(docker ps --format '{{.Names}} {{.Status}}' | grep -c -E 'app1-flask|app2-express|prometheus|grafana|proxy-nginx')
            [ "$UP" -ge 5 ] && break || sleep 5
          done

      - name: Wait for app health (simple retry)
        run: |
          set -e
          for i in {1..50}; do
            curl -fsS http://127.0.0.1:18080/healthz && break || sleep 2
          done
          curl -fsS http://127.0.0.1:15000/hello
          curl -fsS http://127.0.0.1:13000/hello

      - name: Smoke via proxy
        run: |
          ./tests/smoke.sh

      - name: Scrape check (Prometheus targets)
        run: |
          curl -fsS http://127.0.0.1:19090/targets | head -n 50

      - name: Collect logs
        run: |
          mkdir -p artifacts
          docker compose logs --no-color > artifacts/compose-logs.txt || true
          docker ps > artifacts/ps.txt || true

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: artifacts/

      - name: Compose down
        if: always()
        run: docker compose down -v
